author: "Alexey Karapetov <karapetov@gmail.com>"
description: "Tesla API proxy."
homepage: "https://github.com/f3ath/tesla-api"
name: "tesla_proxy"
version: "0.0.1"
executables:
  proxy: "proxy.dart"
dependencies:
  args: "^1.5.0"
  shelf_proxy: "^0.1.0"
  shelf: "^0.7.3"
dev_dependencies:
  test: "^1.3.0"
  mockito: "^3.0.0"
environment:
  sdk: ">=2.0.0 <3.0.0"
